### ISSUE TITLE
Plugin causes page creation error

### ISSUE THREAD

**Issue by DomBickus** [paulmassen/grav-plugin-seo#27]
While creating a new page (parent page to be precise, modular page creation seems fine) gets to an error:
```
Whoops\Exception\ErrorException thrown with message "Cannot use Grav\Common\Utils as Utils because the name is already in use"

Stacktrace:
#0 Whoops\Exception\ErrorException in E:\Testavimo serveris\eds-www\projects\armontus\user\plugins\admin\classes\admincontroller.php:17
```
For testing purposes page created were named test:
![page-creation](https://user-images.githubusercontent.com/25031576/31191138-e9a4dba4-a945-11e7-9f8d-e5e64dc638e8.png)
And then it leads to an error:
![page-creation-error](https://user-images.githubusercontent.com/25031576/31191156-f6f8d4c2-a945-11e7-9f4e-2f96c46ed849.png)

While if the plugin is disabled the page is created normally.

Page environment: Grav v1.3.4 - Admin v1.6.3 - SEOv2.0.8

**Comment by paulmassen** [comment]
I really can't replicate this. Are you using a custom blueprint or does your plugin extend the default one? Does this happen on every blueprint?

**Comment by paulmassen** [comment]
Can you try this commit and let me know if it change something ? https://github.com/paulmassen/grav-plugin-seo/commit/2f039f65382913fc2ba44c69965c1979739e913e

**Comment by paulmassen** [comment]
Oops, I forgot a semicolo: Fixed here https://github.com/paulmassen/grav-plugin-seo/commit/7ebd4ef00e913b620a1aaa675a44e4b4aded6ebe

**Comment by DomBickus** [comment]
@paulmassen all my custom blueprint extends the default. So I don't think that is the problem.

Last commit didn't fix the issue. I really don't have an idea why this happens. I even tried a fresh Grav installation with default Antimatter theme, still the same error.
I could try to upload it to a server and replicate it there and grant access to admin.

**Comment by paulmassen** [comment]
Very weird, I tried on local on windows too, and can't replicate this problem. 

Keep me updated if you have more information!

**Comment by paulmassen** [comment]
Should be fixed in master and in the upcoming 2.0.9 release
